# Generated by Django 5.1.7 on 2025-05-04 07:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning_logs", "0006_aiinteraction_model_used"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_study_time",
                    models.BooleanField(default=True, verbose_name="显示学习时间"),
                ),
                (
                    "show_topic_progress",
                    models.BooleanField(default=True, verbose_name="显示主题进度"),
                ),
                (
                    "show_goal_progress",
                    models.BooleanField(default=True, verbose_name="显示学习目标进度"),
                ),
                (
                    "chart_color_theme",
                    models.CharField(default="default", max_length=50),
                ),
                ("dashboard_layout", models.CharField(default="grid", max_length=20)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "每日报告"),
                            ("weekly", "每周报告"),
                            ("monthly", "每月报告"),
                            ("yearly", "年度报告"),
                            ("custom", "自定义报告"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_study_time", models.DurationField()),
                ("topics_covered", models.PositiveIntegerField()),
                ("entries_created", models.PositiveIntegerField()),
                ("goals_completed", models.PositiveIntegerField()),
                ("data_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="LearningInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("productivity", "生产力洞察"),
                            ("pattern", "学习模式洞察"),
                            ("recommendation", "学习建议"),
                            ("achievement", "成就提醒"),
                            ("streak", "连续性"),
                            ("general", "一般信息"),
                        ],
                        max_length=20,
                        verbose_name="洞察类型",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("message", models.TextField(verbose_name="内容")),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="重要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="当前连续学习天数"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="最长连续学习天数"
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="最后活动日期"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_streaks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_calculated",
                    models.DateField(auto_now=True, verbose_name="最后计算时间"),
                ),
                (
                    "total_study_time",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="总学习时间"
                    ),
                ),
                (
                    "study_frequency",
                    models.PositiveIntegerField(default=0, verbose_name="学习频率"),
                ),
                (
                    "entry_count",
                    models.PositiveIntegerField(default=0, verbose_name="条目数"),
                ),
                (
                    "avg_entry_length",
                    models.FloatField(default=0.0, verbose_name="平均条目长度"),
                ),
                (
                    "last_studied",
                    models.DateField(
                        blank=True, null=True, verbose_name="最后学习时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="learning_logs.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Analytics",
                "verbose_name_plural": "Topic Analytics",
            },
        ),
        migrations.CreateModel(
            name="ProductivityTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour_of_day", models.PositiveIntegerField(verbose_name="小时")),
                (
                    "total_duration",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="总时长"
                    ),
                ),
                (
                    "session_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="会话数"),
                ),
                (
                    "avg_productivity",
                    models.FloatField(default=0.0, verbose_name="平均生产力"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productivity_times",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "hour_of_day")},
            },
        ),
        migrations.CreateModel(
            name="StudyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_study_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("topics_studied", models.PositiveIntegerField(default=0)),
                ("entries_created", models.PositiveIntegerField(default=0)),
                ("goals_completed", models.PositiveIntegerField(default=0)),
                ("ai_interactions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Metric",
                "verbose_name_plural": "Study Metrics",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
