# Generated by Django 5.1.7 on 2025-04-22 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning_logs",
            "0002_studysession_entry_completed_topic_completed_items_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="learninggoal",
            old_name="decription",
            new_name="description",
        ),
        migrations.AddField(
            model_name="studysession",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studysession",
            name="topic",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_sessions",
                to="learning_logs.topic",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studysession",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
