# Generated by Django 5.1.7 on 2025-04-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0005_aiinteraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinteraction",
            name="model_used",
            field=models.CharField(default="llama3", max_length=50),
        ),
    ]
