# Generated by Django 5.1.7 on 2025-04-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="avatar",
            new_name="avatar_url",
        ),
    ]
